require:
  - solidus_extension_dev_tools/rubocop

inherit_gem:
  solidus_extension_dev_tools: .rubocop.extension.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - spec/dummy/**/*
    - vendor/**/*

RSpec/MultipleExpectations:
  Exclude:
    - spec/features/**/*

Rails/SkipsModelValidations:
  Exclude:
    - db/migrate/**/*
